#!/bin/sh

info() {
    printf "\r  [ \033[00;34m..\033[0m ] %s\n" "$1"
}

query() {
    printf "\r  [ \033[0;33m??\033[0m ] %s\n" "$1"
}

success() {
    printf "\r\033[2K  [ \033[00;32mOK\033[0m ] %s\n" "$1"
}

warn() {
    printf "\r\033[2K  [\033[0;33mWARN\033[0m] %s\n" "$1"
}

fail() {
    printf "\r\033[2K  [\033[0;31mFAIL\033[0m] %s\n" "$1"
    exit 1
}

setup_zsh() {
    CURRENT_SHELL=$(echo "$SHELL" | rev | cut -d '/' -f 1 | rev)
    if [ "$CURRENT_SHELL" = "zsh" ]; then
        info "Already using zsh, skipping"
    else
        query "Write to /etc/zsh/zprofile and /etc/zsh/zshenv? [y/n]"
        do_etc_zsh=""
        while [ -z "$do_etc_zsh" ]; do
            read do_etc_zsh
            case $do_etc_zsh in
                y*|Y*)
                    echo "emulate sh -c 'source /etc/profile'" | sudo tee /etc/zsh/zprofile > /dev/null
                    echo 'export ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"' | sudo tee /etc/zsh/zshenv > /dev/null
                    ;;
                n*|N*)
                    ;;
                *)
                    do_etc_zsh=""
                    warn "Invalid option, expecting [y/n]"
            esac
        done

        query "Change shell to zsh? [y/n]"
        use_zsh=""
        while [ -z "$use_zsh" ]; do
            read use_zsh
            case $use_zsh in
                y*|Y*)
                    chsh -s /bin/zsh
                    ;;
                n*|N*)
                    ;;
                *)
                    use_zsh=""
                    warn "Invalid option, expecting [y/n]"
            esac
        done
    fi
    info "Setting up dotfile directory environment variables"
    DOTFILEDIR=$(dirname "$(realpath $0)")
    echo "export DOTFILEDIR=$(echo $DOTFILEDIR | sed "s:$HOME:\$HOME:g")\n"'export WALLPAPERDIR=$DOTFILEDIR/wallpapers' > "${XDG_DATA_HOME:-~/.local/share}/zsh/source/dotfile_vars"
}

setup_zsh
