# Shadow
shadow = true;
shadow-radius = 10;
shadow-offset-x = -4;
shadow-offset-y = -4;
shadow-opacity = 1;
shadow-exclude = [
	"class_g = 'dwm'",
	"class_g = 'ffmpeg'",
	"window_type *= 'normal' && ! name ~= ''",
];

# Window type settings
wintypes: {
  utility = { shadow = false; };
};
