#!/bin/sh

session=${1:-dwm}

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

xrdb "${XDG_CONFIG_HOME:-~/.config}/Xresources"
xmodmap "${XDG_CONFIG_HOME:-~/.config}/Xmodmap"

xsetroot -cursor_name left_ptr    # Make desktop use normal cursor
xset r rate 400 30                # Keyboard repeat rate

dunst &

start-sxhkd "$session" &

export QT_QPA_PLATFORMTHEME=qt5ct # Needed for qt applications to pull their theme from qt5ct

exec "$session"
