# Default style that is applied to all UI elements. A string of ASS override tags.
# Individual elements have their own style settings which override the tags here.
# Changing the font will likely require changing the hover-time margin settings
# and the offscreen-pos settings.
# 
# Here are some useful ASS override tags (omit square brackets):
# \fn[Font Name]: sets the font to the named font.
# \fs[number]: sets the font size to the given number.
# \b[1/0]: sets the text bold or not (\b1 is bold, \b0 is regular weight).
# \i[1/0]: sets the text italic or not (same semantics as bold).
# \bord[number]: sets the outline width to the given number (in pixels).
# \shad[number]: sets the shadow size to the given number (pixels).
# \c&H[BBGGRR]&: sets the fill color for the text to the given color (hex pairs in
# 	             the order, blue, green, red).
# \3c&H[BBGGRR]&: sets the outline color of the text to the given color.
# \4c&H[BBGGRR]&: sets the shadow color of the text to the given color.
# \alpha&H[AA]&: sets the line's transparency as a hex pair. 00 is fully opaque
#                and FF is fully transparent. Some UI elements are composed of
#                multiple layered lines, so adding transparency may not look good.
#                For further granularity, \1a&H[AA]& controls the fill opacity,
#                \3a&H[AA]& controls the outline opacity, and \4a&H[AA]& controls
#                the shadow opacity.
default-style=\fnSource Sans Pro\b1\bord2\shad0\fs30\c&HFC799E&\3c&000000D&

# Hide the bar when you aren't over it
bar-hide-inactive=yes

# Disable title and system time
enable-title=no
enable-system-time=no

# Only show future cached frames
bar-cache-position=underlay

# Bar height (keep these the same)
bar-height-active=8
bar-cache-height-active=8

# Font sizes
elapsed-style=\fs22
remaining-style=\fs22
hover-time-style=\fs20

# Animation speed
animation-duration=0