set preview_images true
set preview_images_method ueberzug

setlocal path=~/downloads sort mtime
setlocal path=~/pictures/android/Camera sort mtime

map cd console z%space
map ci zi

map <C-d> shell dragon -a -x %p 2>/dev/null &

map cr eval fm.execute_console("bulkrename") if fm.thisdir.marked_items else fm.open_console("rename " + fm.thisfile.basename)
map cW shell vidir

map f console scout -ftsea%space
