daemon = true
backend = "glx"
#unredir-if-possible = true
vsync = true
#use-damage = false

corner-radius = 12

# MULTILINE STRINGS ARE ALLOWED
rules: (
    {
        match = "fullscreen && !class_g = 'mpv'"
        # doesn't work?
        vsync = false
    },
    #{
    #    match = "class_g = 'mpv'"
    #    unredir = false
    #},
    {
        match = "fullscreen || class_g = 'awesome' || border_width = 0"
        corner-radius = 0
    },
    {
        #match = "!class_g = 'mpv' && (class_g = 'Zathura' || !fullscreen)"
        match = "!class_g = 'mpv' && !class_g = 'flameshot'"
        #match = "class_g != 'BINGUS'"
        shader = {
            path = "main.glsl"
            defines = {
                GRAIN_ENABLED = "true"
            }
        }
    },
    {
        match = "class_g = 'MComix' && fullscreen"
        shader = {
            path = "main.glsl"
            defines = {
                GRAIN_ENABLED = "true",
                #RECOLOR_ENABLED = "true",
                RECOLOR_GREYSCALE_AWARE = "true"
            }
        }
    },
)
root-pixmap-shader = {
    path = "main.glsl"
        defines = {
            GRAIN_ENABLED = "true"
        }
}

#animations = (
#	{
#		triggers = [ "geometry" ];
#		saved-image-blend = 0;
#		scale-x = {
#			duration = 0.2;
#			curve = "cubic-bezier(0.2, 0.7, 0.3, 1)";
#			start = "window-width-before / window-width";
#			end = 1;
#		};
#		scale-y = {
#			duration = 0.2;
#			curve = "cubic-bezier(0.2, 0.7, 0.3, 1)";
#			start = "window-height-before / window-height";
#			end = 1;
#		};
#		offset-x = {
#			duration = 0.2;
#			curve = "cubic-bezier(0.2, 0.7, 0.3, 1)";
#			start = "window-x-before - window-x";
#			end = 0;
#		};
#		offset-y = {
#			duration = 0.2;
#			curve = "cubic-bezier(0.2, 0.7, 0.3, 1)";
#			start = "window-y-before - window-y";
#			end = 0;
#		};
#		shadow-scale-x = "scale-x";
#		shadow-scale-y = "scale-y";
#		shadow-offset-x = "offset-x";
#		shadow-offset-y = "offset-y";
#	}
#);
