#!/bin/sh

### LAYOUTS ###

# 0 = tile
# 1 = monocle
# 2 = NULL

dwmc viewex 3; dwmc setlayoutex 1
dwmc viewex 4; dwmc setlayoutex 1; dwmc togglebar
dwmc viewex 0

# bootique template that sets gaps and bar padding
sh "${XDG_CACHE_HOME:-$HOME/.cache}/bootique/dwmsettings" 2> /dev/null

###############


### PROGRAMS ###

autostart &
${XDG_CONFIG_HOME:-$HOME/.config}/dwm/bar &

################
