#!/bin/sh

### HELPERS ###

# set colors from Xresources to variables
eval $(xrdb -q | while read -r line; do
    case $line in
        *\*.*|Bspwm.*)
            colorname=${line%%:*}
            colorname=${colorname#*.}
            colorvalue=${line#*:}
            colorvalue=${colorvalue##[[:space:]]}
            printf '%s=%s\n' "$colorname" "$colorvalue"
            ;;
    esac
done)

###############

### PROGRAMS ###

autostart &
start-polybar

#################


### WORKSPACES ###

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

##################


### WINDOW SETTINGS ###

bspc config border_width          0
bspc config window_gap            10
bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config ignore_ewmh_focus     true

#######################


### WINDOW RULES ###

CURRENT_DESKTOP=$(bspc query -D -d focused)

bspc rule -a Emacs state=tiled

bspc rule -a Emacs:org-capture state=floating
bspc rule -a Emacs:org-agenda state=floating
bspc rule -a Godot state=floating # effects all godot windows, figure out how to do only game window

bspc rule -a mpv state=pseudo_tiled

bspc rule -a Godot desktop='^3'
bspc rule -a zeal desktop='^3'

bspc desktop -f 4; bspc desktop -l monocle
bspc rule -a discord desktop='^4'
bspc rule -a Caprine desktop='^4'
bspc rule -a weechat desktop='^4'

bspc desktop -f 5; bspc desktop -l monocle
bspc rule -a Lutris desktop='^5'
bspc rule -a retroarch desktop='^5'
bspc rule -a Steam desktop='^5'

bspc rule -a qBittorrent desktop='^10'

bspc rule -a twitch-chat split_ratio=0.2

bspc desktop -f "$CURRENT_DESKTOP"

####################
