# Volume control
WHEEL_UP add volume 5
WHEEL_DOWN add volume -5
UP add volume 5
DOWN add volume -5

# Subtitle delay
Z add sub-delay -1
X add sub-delay 1
Ctrl+z add sub-delay -60
Ctrl+x add sub-delay 60
Ctrl+Z add sub-delay -3600
Ctrl+X add sub-delay 3600

# Zoom
- add video-zoom -0.001
= add video-zoom 0.001
Alt+- add video-zoom -0.01
Ctrl+Alt+- add video-zoom -0.05
Alt+= add video-zoom 0.01
Ctrl+Alt+= add video-zoom 0.05

# Seeking
RIGHT no-osd seek 5 exact; script-binding progressbar/request-display
Shift+RIGHT ignore
Ctrl+RIGHT ignore
. frame-step

LEFT no-osd seek -5 exact; script-binding progressbar/request-display
Shift+LEFT ignore
Ctrl+LEFT ignore
, frame-back-step

HOME no-osd sub-seek -1
END no-osd sub-seek 1

# Toggle sub style override
o cycle-values sub-ass-override force no

# Copy current frame to clipboard (without shaders)
Ctrl+c no-osd screenshot-to-file /tmp/current_frame.png subtitles; show-text "Frame copied with subtitles"; run "/bin/sh" "-c" "sleep 0.1 && xclip -sel clip -t image/png /tmp/current_frame.png && rm -f /tmp/current_frame.png"
Ctrl+Shift+c no-osd screenshot-to-file /tmp/current_frame_no_subs.png video; show-text "Frame copied without subtitles"; run "/bin/sh" "-c" "sleep 0.1 && xclip -sel clip -t image/png /tmp/current_frame_no_subs.png && rm -f /tmp/current_frame_no_subs.png"

# Pause with K
k cycle pause
