###General###
profile=gpu-hq
vo=gpu
gpu-api=vulkan
vulkan-async-compute
cursor-autohide=100
keep-open=yes
osc=no
osd-bar=no
osd-font-size=16
osd-border-size=2

###Lang Priority###
slang=eng
alang=jpn,eng

###Audio###
ao=alsa
volume=60
volume-max=200

###Subs###
#sub-ass-shaper=complex
#blend-subtitles=yes
demuxer-mkv-subtitle-preroll=yes
sub-ass-vsfilter-blur-compat=no
sub-fix-timing=yes
sub-gauss=0.0
sub-gray=yes
#sub-ass-force-style=FontName=Open Sans Semibold,OutlineColour=00000000 # Use to override font style without altering typesetting
sub-font=Open Sans Semibold
sub-font-size=54
sub-blur=0.0
sub-bold=yes
sub-border-color=0.0/0.0/0.0/1.0
sub-border-size=2.55
sub-color=1.0/1.0/1.0/1.0
sub-margin-x=100
sub-margin-y=50
sub-shadow-color=0.0/0.0/0.0/1.0
sub-shadow-offset=0

###Screenshot###
screenshot-format=png
screenshot-high-bit-depth=yes
screenshot-png-compression=1
screenshot-jpeg-quality=95
screenshot-directory="~/pictures/mpv/"

###Dither###
dither-depth=no

###Deband###
deband=no
deband-iterations=4
deband-threshold=50
deband-range=16
deband-grain=0

###Grain & Resizer###
glsl-shader="~~/shaders/noise_static_luma.hook"
#glsl-shaders="~/shaders/Anime4K_Adaptive.glsl"
# glsl-shader="~~/shaders/Anime4K_Hybrid_v2.0RC5.glsl"
#glsl-shader="~/.config/mpv/shaders/ravu-r4.hook"
#glsl-shader="~/.config/mpv/shaders/FSRCNNX_x2_16-0-4-1.glsl"
# scale=ewa_lanczossharp
# scale=ewa_lanczos
# dscale=ewa_lanczos
fbo-format=rgba16hf
#no-scaler-resizes-only

###Resizer###
#scale=ewa_lanczossharp
#dscale=ewa_lanczos
#cscale=ewa_lanczossoft
#scale=catmull_rom
#dscale=bicubic_fast
#cscale=sinc
#cscale-window=blackman
#cscale-radius=3

[HorribleSubs]
profile-desc=cond:string.match(p.filename, "HorribleSubs")~=nil
deband=yes

[EraiRaws]
profile-desc=cond:string.match(p.filename, "Erai%-raws")~=nil
deband=yes
