### General
cursor-autohide=100
keep-open=yes
osc=no
osd-bar=no
osd-font-size=16
osd-border-size=2

### Video
profile=gpu-hq
vo=gpu
gpu-api=vulkan
vulkan-async-compute
dither-depth=auto

### Audio
ao=alsa
volume=70
volume-max=200

slang=eng
alang=jpn,eng

### Subs
demuxer-mkv-subtitle-preroll=yes
sub-fix-timing=yes

sub-gray=yes # greyscales DVD subs

# Use to override font style without altering typesetting
# only useful for a select few things situations where normal override breaks things
#sub-ass-force-style=FontName=Open Sans Semibold,OutlineColour=00000000

# Subtitle styles for overriding or fallback when there is no styling
sub-font=Open Sans Semibold
sub-font-size=54
sub-blur=0.0
sub-bold=yes
sub-border-color=0.0/0.0/0.0/1.0
sub-border-size=2.55
sub-color=1.0/1.0/1.0/1.0
sub-margin-x=100
sub-margin-y=50
sub-shadow-color=0.0/0.0/0.0/1.0
sub-shadow-offset=0

### Screenshot
screenshot-format=png
screenshot-high-bit-depth=yes
screenshot-png-compression=1
screenshot-directory="~/opt/pictures/mpv/"
